### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ZHassanQ** [JamesIsWack/bgtoolset-mirror#1]
Is this an official mirror of bgtoolset or it is all programmed by yourself trying to make a copy of it.

**Comment by JamesIsWack** [comment]
hey mate, and thanks for making a issue!
this is a mirror of the toolset, no code has been modifed. do not use this, it is potentially unsafe due to missing protection files. it will cause a softbrick on all consoles (including NANDs). please wait until either: 1) bg re releases the toolset, or 2) kostirez1 releases his PSLIGHT homebrew patcher, which runs on PS3HEN. this willl be the safest and most reliable way to jailbreak consoles ever since the E3 FLASHER methods from way back when. until then use PS3HEN. it will suffice if you dont need CFW specific features. also, when you do install CFW, please use EVILNAT 4.89.3, its a very stable CFW. it now has DEX features, as well as some overall QoL improvements, like COBRA Failsafe, which checks whether or not emer_init.self has been run, then mounts dev_blind and renames stage2.cex (or .dex) to stage2.cex.bak. use this in cordination with MAMBA, which should be available with webMAN MOD. you should then be able to re enable COBRA with multiMANs mmOS, by mounting dev_blind and removing the .bak from stage2 in dev_blind/sys/

hope you had a good holiday,
James

**Comment by ZHassanQ** [comment]
Thank you so much for replying I will keep that in mind. Happy Holidays!

**Comment by JamesIsWack** [comment]
> Thank you so much for replying I will keep that in mind. Happy Holidays!

hey mate, ik you closed the issue but i have the chance to let you know about my discord server since im off holliday.
permanent invite: https://discord.gg/UjxdYB2xSm 
spread it around! its a playstation homebrew server, im only doing PS3 stuff, i can help you there if you need it. or just hang out.
